### ISSUE TITLE
Unhandled exception thrown: read access violation. base was nullptr.

### ISSUE THREAD

**Issue by ms3c** [skadro-official/skCrypter#1]
Hello I was using the function CryptStringToBinaryA. The program compiles and execute but I Can't get results if I put it in debugger I got this exception Unhandled exception thrown: read access violation. base was nullptr.
![image](https://user-images.githubusercontent.com/37941160/178113699-9ef4e73d-c3b1-4ff6-af1d-36430055d7b4.png)

![image](https://user-images.githubusercontent.com/37941160/178113709-4c187b11-0086-42a8-bd1b-2c6e7f45bf8e.png)

**Comment by hexappp** [comment]
add LI_FN(LoadLibrayA)("crypt32.dll"); before CryptStringToBinaryA

**Comment by hexappp** [comment]
and this is not the skCrypter issue, if you wrote this issue to LazyImporter, it would have been answered before

**Comment by ms3c** [comment]
Alright thanks, let me test then i'll provide feedback.
